# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-20201216/bin/cmake

# The command to remove a file.
RM = /opt/cmake-20201216/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roman/Projects/plot-cv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roman/Projects/plot-cv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake-20201216/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake-20201216/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake-20201216/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake-20201216/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-20201216/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake-20201216/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake-20201216/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-20201216/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/roman/Projects/plot-cv && $(CMAKE_COMMAND) -E cmake_progress_start /home/roman/Projects/plot-cv/CMakeFiles /home/roman/Projects/plot-cv/quickjs/qjs-net//CMakeFiles/progress.marks
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quickjs/qjs-net/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roman/Projects/plot-cv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quickjs/qjs-net/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quickjs/qjs-net/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quickjs/qjs-net/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/roman/Projects/plot-cv && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/rule:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/rule
.PHONY : quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/rule

# Convenience name for target.
quickjs-minnet: quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/rule
.PHONY : quickjs-minnet

# fast build rule for target.
quickjs-minnet/fast:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build
.PHONY : quickjs-minnet/fast

# Convenience name for target.
quickjs/qjs-net/CMakeFiles/libwebsockets.dir/rule:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quickjs/qjs-net/CMakeFiles/libwebsockets.dir/rule
.PHONY : quickjs/qjs-net/CMakeFiles/libwebsockets.dir/rule

# Convenience name for target.
libwebsockets: quickjs/qjs-net/CMakeFiles/libwebsockets.dir/rule
.PHONY : libwebsockets

# fast build rule for target.
libwebsockets/fast:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/libwebsockets.dir/build.make quickjs/qjs-net/CMakeFiles/libwebsockets.dir/build
.PHONY : libwebsockets/fast

buffer.o: buffer.c.o
.PHONY : buffer.o

# target to build an object file
buffer.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/buffer.c.o
.PHONY : buffer.c.o

buffer.i: buffer.c.i
.PHONY : buffer.i

# target to preprocess a source file
buffer.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/buffer.c.i
.PHONY : buffer.c.i

buffer.s: buffer.c.s
.PHONY : buffer.s

# target to generate assembly for a file
buffer.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/buffer.c.s
.PHONY : buffer.c.s

jsutils.o: jsutils.c.o
.PHONY : jsutils.o

# target to build an object file
jsutils.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/jsutils.c.o
.PHONY : jsutils.c.o

jsutils.i: jsutils.c.i
.PHONY : jsutils.i

# target to preprocess a source file
jsutils.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/jsutils.c.i
.PHONY : jsutils.c.i

jsutils.s: jsutils.c.s
.PHONY : jsutils.s

# target to generate assembly for a file
jsutils.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/jsutils.c.s
.PHONY : jsutils.c.s

minnet-client.o: minnet-client.c.o
.PHONY : minnet-client.o

# target to build an object file
minnet-client.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-client.c.o
.PHONY : minnet-client.c.o

minnet-client.i: minnet-client.c.i
.PHONY : minnet-client.i

# target to preprocess a source file
minnet-client.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-client.c.i
.PHONY : minnet-client.c.i

minnet-client.s: minnet-client.c.s
.PHONY : minnet-client.s

# target to generate assembly for a file
minnet-client.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-client.c.s
.PHONY : minnet-client.c.s

minnet-fetch.o: minnet-fetch.c.o
.PHONY : minnet-fetch.o

# target to build an object file
minnet-fetch.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-fetch.c.o
.PHONY : minnet-fetch.c.o

minnet-fetch.i: minnet-fetch.c.i
.PHONY : minnet-fetch.i

# target to preprocess a source file
minnet-fetch.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-fetch.c.i
.PHONY : minnet-fetch.c.i

minnet-fetch.s: minnet-fetch.c.s
.PHONY : minnet-fetch.s

# target to generate assembly for a file
minnet-fetch.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-fetch.c.s
.PHONY : minnet-fetch.c.s

minnet-request.o: minnet-request.c.o
.PHONY : minnet-request.o

# target to build an object file
minnet-request.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-request.c.o
.PHONY : minnet-request.c.o

minnet-request.i: minnet-request.c.i
.PHONY : minnet-request.i

# target to preprocess a source file
minnet-request.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-request.c.i
.PHONY : minnet-request.c.i

minnet-request.s: minnet-request.c.s
.PHONY : minnet-request.s

# target to generate assembly for a file
minnet-request.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-request.c.s
.PHONY : minnet-request.c.s

minnet-response.o: minnet-response.c.o
.PHONY : minnet-response.o

# target to build an object file
minnet-response.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-response.c.o
.PHONY : minnet-response.c.o

minnet-response.i: minnet-response.c.i
.PHONY : minnet-response.i

# target to preprocess a source file
minnet-response.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-response.c.i
.PHONY : minnet-response.c.i

minnet-response.s: minnet-response.c.s
.PHONY : minnet-response.s

# target to generate assembly for a file
minnet-response.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-response.c.s
.PHONY : minnet-response.c.s

minnet-server-http.o: minnet-server-http.c.o
.PHONY : minnet-server-http.o

# target to build an object file
minnet-server-http.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server-http.c.o
.PHONY : minnet-server-http.c.o

minnet-server-http.i: minnet-server-http.c.i
.PHONY : minnet-server-http.i

# target to preprocess a source file
minnet-server-http.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server-http.c.i
.PHONY : minnet-server-http.c.i

minnet-server-http.s: minnet-server-http.c.s
.PHONY : minnet-server-http.s

# target to generate assembly for a file
minnet-server-http.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server-http.c.s
.PHONY : minnet-server-http.c.s

minnet-server-proxy.o: minnet-server-proxy.c.o
.PHONY : minnet-server-proxy.o

# target to build an object file
minnet-server-proxy.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server-proxy.c.o
.PHONY : minnet-server-proxy.c.o

minnet-server-proxy.i: minnet-server-proxy.c.i
.PHONY : minnet-server-proxy.i

# target to preprocess a source file
minnet-server-proxy.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server-proxy.c.i
.PHONY : minnet-server-proxy.c.i

minnet-server-proxy.s: minnet-server-proxy.c.s
.PHONY : minnet-server-proxy.s

# target to generate assembly for a file
minnet-server-proxy.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server-proxy.c.s
.PHONY : minnet-server-proxy.c.s

minnet-server-ws.o: minnet-server-ws.c.o
.PHONY : minnet-server-ws.o

# target to build an object file
minnet-server-ws.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server-ws.c.o
.PHONY : minnet-server-ws.c.o

minnet-server-ws.i: minnet-server-ws.c.i
.PHONY : minnet-server-ws.i

# target to preprocess a source file
minnet-server-ws.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server-ws.c.i
.PHONY : minnet-server-ws.c.i

minnet-server-ws.s: minnet-server-ws.c.s
.PHONY : minnet-server-ws.s

# target to generate assembly for a file
minnet-server-ws.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server-ws.c.s
.PHONY : minnet-server-ws.c.s

minnet-server.o: minnet-server.c.o
.PHONY : minnet-server.o

# target to build an object file
minnet-server.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server.c.o
.PHONY : minnet-server.c.o

minnet-server.i: minnet-server.c.i
.PHONY : minnet-server.i

# target to preprocess a source file
minnet-server.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server.c.i
.PHONY : minnet-server.c.i

minnet-server.s: minnet-server.c.s
.PHONY : minnet-server.s

# target to generate assembly for a file
minnet-server.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-server.c.s
.PHONY : minnet-server.c.s

minnet-stream.o: minnet-stream.c.o
.PHONY : minnet-stream.o

# target to build an object file
minnet-stream.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-stream.c.o
.PHONY : minnet-stream.c.o

minnet-stream.i: minnet-stream.c.i
.PHONY : minnet-stream.i

# target to preprocess a source file
minnet-stream.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-stream.c.i
.PHONY : minnet-stream.c.i

minnet-stream.s: minnet-stream.c.s
.PHONY : minnet-stream.s

# target to generate assembly for a file
minnet-stream.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-stream.c.s
.PHONY : minnet-stream.c.s

minnet-websocket.o: minnet-websocket.c.o
.PHONY : minnet-websocket.o

# target to build an object file
minnet-websocket.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-websocket.c.o
.PHONY : minnet-websocket.c.o

minnet-websocket.i: minnet-websocket.c.i
.PHONY : minnet-websocket.i

# target to preprocess a source file
minnet-websocket.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-websocket.c.i
.PHONY : minnet-websocket.c.i

minnet-websocket.s: minnet-websocket.c.s
.PHONY : minnet-websocket.s

# target to generate assembly for a file
minnet-websocket.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet-websocket.c.s
.PHONY : minnet-websocket.c.s

minnet.o: minnet.c.o
.PHONY : minnet.o

# target to build an object file
minnet.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet.c.o
.PHONY : minnet.c.o

minnet.i: minnet.c.i
.PHONY : minnet.i

# target to preprocess a source file
minnet.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet.c.i
.PHONY : minnet.c.i

minnet.s: minnet.c.s
.PHONY : minnet.s

# target to generate assembly for a file
minnet.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/minnet.c.s
.PHONY : minnet.c.s

poll.o: poll.c.o
.PHONY : poll.o

# target to build an object file
poll.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/poll.c.o
.PHONY : poll.c.o

poll.i: poll.c.i
.PHONY : poll.i

# target to preprocess a source file
poll.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/poll.c.i
.PHONY : poll.c.i

poll.s: poll.c.s
.PHONY : poll.s

# target to generate assembly for a file
poll.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/build.make quickjs/qjs-net/CMakeFiles/quickjs-minnet.dir/poll.c.s
.PHONY : poll.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... libwebsockets"
	@echo "... quickjs-minnet"
	@echo "... buffer.o"
	@echo "... buffer.i"
	@echo "... buffer.s"
	@echo "... jsutils.o"
	@echo "... jsutils.i"
	@echo "... jsutils.s"
	@echo "... minnet-client.o"
	@echo "... minnet-client.i"
	@echo "... minnet-client.s"
	@echo "... minnet-fetch.o"
	@echo "... minnet-fetch.i"
	@echo "... minnet-fetch.s"
	@echo "... minnet-request.o"
	@echo "... minnet-request.i"
	@echo "... minnet-request.s"
	@echo "... minnet-response.o"
	@echo "... minnet-response.i"
	@echo "... minnet-response.s"
	@echo "... minnet-server-http.o"
	@echo "... minnet-server-http.i"
	@echo "... minnet-server-http.s"
	@echo "... minnet-server-proxy.o"
	@echo "... minnet-server-proxy.i"
	@echo "... minnet-server-proxy.s"
	@echo "... minnet-server-ws.o"
	@echo "... minnet-server-ws.i"
	@echo "... minnet-server-ws.s"
	@echo "... minnet-server.o"
	@echo "... minnet-server.i"
	@echo "... minnet-server.s"
	@echo "... minnet-stream.o"
	@echo "... minnet-stream.i"
	@echo "... minnet-stream.s"
	@echo "... minnet-websocket.o"
	@echo "... minnet-websocket.i"
	@echo "... minnet-websocket.s"
	@echo "... minnet.o"
	@echo "... minnet.i"
	@echo "... minnet.s"
	@echo "... poll.o"
	@echo "... poll.i"
	@echo "... poll.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/roman/Projects/plot-cv && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

